/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.HillClimb;
import Model.MyHillClimb;
import Model.RoadState;
import Model.State;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author minh0
 */
public class ViewHillClimb extends javax.swing.JFrame {
    
    private Surface s ;
    
    private List<State> dsDinh;
    private List<State> dsKT;
    private State dinhBD;
    private List<RoadState> dsDD;
    
    private MyHillClimb core;
    /**
     * Creates new form Test
     */
    public ViewHillClimb() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Thuật toán tìm kiếm leo đồi trong đồ thị");
        s = new Surface(this);
        //s.setMainview(this);
        //s.setSize(1000, 1000);
        //s.setBounds(0, 0, 1000, 1000);
        //s.setVisible(true);
        JScrollPane js = new JScrollPane(s, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        js.setBounds(jPanel1.getBounds());
        js.setLocation(0, 0);
        Dimension d = new Dimension(2000, 2000);
        s.setPreferredSize(d);
        s.revalidate();
        jPanel1.add(js);
        dsDinh = new ArrayList<>();
        dsDD = new ArrayList<>();
        dinhBD = new State();
        dsKT = new ArrayList<>();
        List<HillClimb> dshcl = new ArrayList<>();
        List<State> roadsearch =  new ArrayList<>();
        Stack<State> MOs = new Stack<>();
        core = new MyHillClimb(dinhBD,dsKT,dsDinh,dsDD,dshcl,roadsearch,MOs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuckHuong = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbDinhDau = new javax.swing.JComboBox<>();
        cbDinhDich = new javax.swing.JComboBox<>();
        txtTenDinh = new javax.swing.JTextField();
        btnLuuDinh = new javax.swing.JButton();
        btStep = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNoiDinh = new javax.swing.JButton();
        ckbBatDau = new javax.swing.JCheckBox();
        ckbKetThuc = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinTrongSo = new javax.swing.JSpinner();
        spinTT = new javax.swing.JSpinner();
        lbstart = new javax.swing.JLabel();
        lbend = new javax.swing.JLabel();
        btnXoaDinh = new javax.swing.JButton();
        btnXoaNoi = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        checkbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSDinh = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBCGiai = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taKetLuan = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        menuckHuong.setText("Đồ thị vô hướng");
        jPopupMenu1.add(menuckHuong);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Tên đỉnh");

        jLabel2.setText("Trạng thái");

        jLabel4.setText("ĐỈnh cuối");

        cbDinhDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDinhDich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTenDinh.setToolTipText("Nhập tên đỉnh");

        btnLuuDinh.setText("Lưu đỉnh");
        btnLuuDinh.setToolTipText("Lưu thông tin đỉnh");
        btnLuuDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDinhActionPerformed(evt);
            }
        });

        btStep.setText("Step");
        btStep.setToolTipText("Chạy từng bước");
        btStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStepActionPerformed(evt);
            }
        });

        btnRun.setText("Run");
        btnRun.setToolTipText("Chạy toàn bộ");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Xóa đồ thị");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNoiDinh.setText("Nối đỉnh");
        btnNoiDinh.setToolTipText("Nối đỉnh");
        btnNoiDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiDinhActionPerformed(evt);
            }
        });

        ckbBatDau.setText("là đỉnh bắt đầu");

        ckbKetThuc.setText("là đỉnh kết thúc");

        jLabel3.setText("Đỉnh đầu ");

        jLabel5.setText("Trọng số");

        lbstart.setText("Đỉnh bắt đầu:");

        lbend.setText("Đỉnh kết thúc:");

        btnXoaDinh.setText("Xóa đỉnh");
        btnXoaDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDinhActionPerformed(evt);
            }
        });

        btnXoaNoi.setText("Xóa nối");
        btnXoaNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNoiActionPerformed(evt);
            }
        });

        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        checkbtn.setText("check");
        checkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDinh)
                            .addComponent(spinTT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaDinh)
                            .addComponent(btnLuuDinh)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ckbBatDau)
                        .addGap(18, 18, 18)
                        .addComponent(ckbKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDinhDau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDinhDich, 0, 132, Short.MAX_VALUE)
                                    .addComponent(spinTrongSo)))
                            .addComponent(lbstart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNoiDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaNoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(checkbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(65, 65, 65))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbDinhDau, cbDinhDich, spinTT, txtTenDinh});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btStep, btnDelete, btnRestart, btnRun});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuDinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDinh))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbKetThuc)
                    .addComponent(ckbBatDau))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDinhDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnNoiDinh))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDinhDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaNoi))))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinTrongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbstart)
                        .addGap(14, 14, 14)
                        .addComponent(lbend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(checkbtn)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRun)
                    .addComponent(btStep, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnRestart))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btStep, btnDelete, btnRestart, btnRun});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbDinhDau, cbDinhDich, spinTT, txtTenDinh});

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đỉnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

        tblDSDinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên đỉnh", "h(m)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDSDinh);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bước Làm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

        tblBCGiai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N", "S", "Child(S)", "MO", "DONG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBCGiai);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        taKetLuan.setEditable(false);
        taKetLuan.setColumns(20);
        taKetLuan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taKetLuan.setRows(1);
        jScrollPane3.setViewportView(taKetLuan);

        jLabel7.setText("Kết luận:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDinhActionPerformed
        if(!core.isIsRunning()){
        int index = s.getClicking();
        if(index < 0){
            JOptionPane.showMessageDialog(this,"Chưa chọn đỉnh");
        }else{
            String nameS = txtTenDinh.getText().trim();
            int tt = (int) spinTT.getModel().getValue();
            if(nameS.compareTo("")==0||nameS==null){
                
            }else{
                State s = new State(nameS, tt);
                if(core.checkinList(s, core.getHm())){
                    //check xem có cùng vị trí ko nếu cùng vị trí thì cho pháp sủa
                    if(index == core.getindexList(s, core.getHm())){
                        if(loadinforbdkt()==1){
                            JOptionPane.showMessageDialog(this,"Đỉnh không hợp lệ");
                        }else{
                            core.fixState(index, s);
                            core.setStartEnds(index, loadinforbdkt());
                            this.s.fixStateint(index, s);
                            this.s.repaint();
                        }
                    }else{
                        JOptionPane.showMessageDialog(this,"Tên đỉnh đã tồn tại");
                    }
                    
                }else{
                    if(loadinforbdkt()==1){
                        JOptionPane.showMessageDialog(this,"Đỉnh không hợp lệ");
                    }else{
                        core.fixState(index, s);
                        core.setStartEnds(index, loadinforbdkt());
                        this.s.fixStateint(index, s);
                        this.s.repaint();
                    }
                }
            }
            
            loadCB();
        }
        }else{
            JOptionPane.showMessageDialog(this,"Không thể thao tác khí đang chạy thuật toán");
        }
        setlbText();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuDinhActionPerformed

    private void checkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbtnActionPerformed
        System.out.println("hm:" + core.getHm());
        System.out.println("road "+core.getRoadStates());
        System.out.println("start "+ core.getStarts());
        System.out.println("ends "+core.getEnds());
        System.out.println("Road "+core.roadString());
        System.out.println("Hill climb "+core.getDs());
        System.out.println("Hill climb "+core.getDs().get(0).DONGString());
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbtnActionPerformed

    private void btnNoiDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiDinhActionPerformed
        if(!core.isIsRunning()){
            
        int indexDau = cbDinhDau.getSelectedIndex();
        int indexDich = cbDinhDich.getSelectedIndex();
        if(indexDau==indexDich||core.getHm()==null||core.getHm().isEmpty()){
            
        }else{
            if(Controller.getController().checkRoad(core.getHm().get(indexDau), core.getHm().get(indexDich), core)){
                int tt = (int) spinTrongSo.getModel().getValue();
                core.fixRoad(core.getHm().get(indexDau), core.getHm().get(indexDich), tt);
                s.fixRoadState(core.getHm().get(indexDau), core.getHm().get(indexDich), tt);
                s.repaint();
            }else{
                RoadState rs = new RoadState(core.getHm().get(indexDau), core.getHm().get(indexDich), (int) spinTrongSo.getModel().getValue());
                core.addRoad(rs);
                s.addDes(s.getDs().get(indexDau), s.getDs().get(indexDich), rs);
                s.repaint();
            }
        }
        }else{
            JOptionPane.showMessageDialog(this,"Không thể thao tác khí đang chạy thuật toán");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnNoiDinhActionPerformed

    private void btnXoaDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDinhActionPerformed
        if(!core.isIsRunning()){

        int index = s.getClicking();
        if(index <= -1){
            
        }else{
            int ck = JOptionPane.showConfirmDialog(this, "Xóa đỉnh "+core.getHm().get(index).getNameState(), "Xác nhận", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if(ck==JOptionPane.OK_OPTION){
                 core.removeState(index);
                 this.s.removeState(index);
                 repaint();
            }else{
                
            }
        }
        
        loadCB();
        }else{
            JOptionPane.showMessageDialog(this,"Không thể thao tác khí đang chạy thuật toán");
        }
        setlbText();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaDinhActionPerformed

    private void btnXoaNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNoiActionPerformed
        if(!core.isIsRunning()){
        int index = cbDinhDau.getSelectedIndex();
        int indexS = cbDinhDich.getSelectedIndex();
        if(index==indexS){
            
        }else{
            core.removeRoad(core.getHm().get(index), core.getHm().get(indexS));
            s.removeRoadState(core.getHm().get(index), core.getHm().get(indexS));
            s.repaint();
        }
        }else{
            JOptionPane.showMessageDialog(this,"Không thể thao tác khí đang chạy thuật toán");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNoiActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        //Kiểm tra xem có tồn tại đỉnh start , có des ko , co đỉnh end ko
        if(core.getStarts().getNameState()==null||core.getEnds().isEmpty()){
            JOptionPane.showMessageDialog(this,"Chưa đủ dữ liệu bài toán");
        }else{
        core.AllHillClimb();
        Controller.getController().loadtblBC(tblBCGiai, core);
        s.repaint();
        if(core.getRoadsearch()==null||core.getRoadsearch().isEmpty()){
            taKetLuan.setText("Không tìm thấy đường đi");
        }else{
            taKetLuan.setText("Đã tìm thấy đường đi: \n"+core.roadString());
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRunActionPerformed

    private void btStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStepActionPerformed
        //Kiểm tra xem có tồn tại đỉnh start , có des ko , co đỉnh end ko
        if(core.getStarts().getNameState()==null||core.getEnds().isEmpty()){
            JOptionPane.showMessageDialog(this,"Chưa đủ dữ liệu bài toán");
        }else{

        core.StepHillClimb();
        Controller.getController().loadtblBC(tblBCGiai, core);
        s.repaint();
        if(core.isIsEnds()){
            if(core.getRoadsearch()==null||core.getRoadsearch().isEmpty()){
                taKetLuan.setText("Không tìm thấy đường đi");
            }else{
                taKetLuan.setText("Đã tìm thấy đường đi: \n"+core.roadString());
            }
        }else{
            
        }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btStepActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        core.restartall();
        Controller.getController().loadtblBC(tblBCGiai, core);
        s.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        core.resetall();
        loadCB();
        Controller.getController().loadtblBC(tblBCGiai, core);
        s.resetView();
        s.repaint();
        taKetLuan.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setlbText(){
        lbstart.setText("Đỉnh bắt đầu: "+core.startString());
        lbend.setText("Đỉnh kết thúc: "+core.EndsString());
    }
    public String getTenDinh(){
        return txtTenDinh.getText().trim();
    }
    public int getTrangThai(){
        return (int) spinTT.getModel().getValue();
    }

    public MyHillClimb getCore() {
        return core;
    }
    public void loadCB(){
        Controller.getController().loadcbDINH(cbDinhDau, core);
        Controller.getController().loadcbDINH(cbDinhDich, core);
        Controller.getController().loadtblDinh(tblDSDinh, core);
    }
    
    public void loadinforState(State s){
        txtTenDinh.setText(s.getNameState());
        spinTT.getModel().setValue(s.getNumofState());
    }
    public void loadinforRoad(RoadState rs){
        
    }
    public void setRoad(int index){
        int tts = core.getindexStart(index);
        int tte = core.getindexEnd(index);
        cbDinhDau.setSelectedIndex(tts);
        cbDinhDich.setSelectedIndex(tte);
        spinTrongSo.setValue(core.getRoadStates().get(index).getCost());
    }
    public int loadinforbdkt(){
        int i=0;
        if(ckbBatDau.isSelected() && ckbKetThuc.isSelected()){
            i=1;
        }else if(!ckbBatDau.isSelected() && ckbKetThuc.isSelected()){
            i=2;
        }else if(ckbBatDau.isSelected() && !ckbKetThuc.isSelected()){
            i=3;
        }else{
            i=4;
        }
        return i;
    }
    public void setckbBdKt(int kt){
        switch (kt){
            case 1:
                ckbBatDau.setSelected(true);
                ckbKetThuc.setSelected(true);
                break;
            case 2:
                ckbBatDau.setSelected(false);
                ckbKetThuc.setSelected(true);
                break;
            case 3:
                ckbBatDau.setSelected(true);
                ckbKetThuc.setSelected(false);
                break;
            default:
                ckbBatDau.setSelected(false);
                ckbKetThuc.setSelected(false);
                break;
        }
                    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHillClimb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHillClimb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHillClimb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHillClimb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHillClimb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStep;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLuuDinh;
    private javax.swing.JButton btnNoiDinh;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnXoaDinh;
    private javax.swing.JButton btnXoaNoi;
    private javax.swing.JComboBox<String> cbDinhDau;
    private javax.swing.JComboBox<String> cbDinhDich;
    private javax.swing.JButton checkbtn;
    private javax.swing.JCheckBox ckbBatDau;
    private javax.swing.JCheckBox ckbKetThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbend;
    private javax.swing.JLabel lbstart;
    private javax.swing.JCheckBoxMenuItem menuckHuong;
    private javax.swing.JSpinner spinTT;
    private javax.swing.JSpinner spinTrongSo;
    private javax.swing.JTextArea taKetLuan;
    private javax.swing.JTable tblBCGiai;
    private javax.swing.JTable tblDSDinh;
    private javax.swing.JTextField txtTenDinh;
    // End of variables declaration//GEN-END:variables
}
